# Generated by Django 5.0.6 on 2024-06-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('instrument', models.CharField(max_length=40)),
                ('musicians', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album_app.a_model')),
            ],
        ),
    ]
